### ISSUE TITLE
Improve placeholders and variables in the model config

### ISSUE THREAD

**Issue by tristanheywood** [nicolas-chaulet/deeppointcloud-benchmarks#46]
Right now the only placeholder supported is 'FEAT', the number of input features. This placeholder needs to be resolved by each model separately. 

It would be better to resolve all placeholders as part of the core of the framework, so that model implementations don't need to worry about it. We could also allow users to do arithmetic in any of the fields (.e.g nn: [64, 64*2]). 

We could also have a 'define_placeholders' section of the config where users can create their own placeholders. E.g. 

```
MyModel:
    type: RSConv
    define_placeholders:
        L1_OUT: 64
    down_conv:
         nn: [[FEAT, 32, L1_OUT], [L1_OUT, L1_OUT*2, 64]
```
