### ISSUE TITLE
Configuration feedback

### ISSUE THREAD

**Issue by omry** [nicolas-chaulet/deeppointcloud-benchmarks#78]
Hi,
I am the author of Hydra. Thanks for using it!
Some feedback about your configuration:

In [segmentation.yaml](https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/blob/004ca013e2525e0eb0466fde55f6a0f7a2c12209/conf/models/segmentation.yaml), you have a bunch of different models.

A better modeling of the config would (probably) be to use composition to select which segmentation model you are using, and have each one is a different file.

This will work well if you are only using a single model at a time (Without looking at the code, that's most likely the case).

**Comment by tchaton** [comment]
Hey @omry,

Thanks for contacting us and having a look to our config files.
We really like Hydra and I have been waited for this tool for a long time.

Yes, that's something we wanted to add, but I had some trouble with hydra.

1. In https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/blob/master/conf/config.yaml
For example, I tried
```
defaults:
    - models: {experiment.task}
```
which didn't work

2. It didn't seem list worked out of the defaults

3. I wanted to separate everything in subfiles as in the example, and add some trouble.

I went to have a look at the source code, but I didn't have much time to spend on it.
I will try to have a second look when we are finished with testing the different models and we release v1 of the code :)

**Comment by omry** [comment]
@tchaton, can you join the [Hydra chat](https://hydra-framework.zulipchat.com/)? 
It will be easier to understand what you are trying to do there.

**Comment by omry** [comment]
The correct way to change the default from the command line is directly changing models:
```
python foo.py models=XYZ
```
At the moment it's not possible to have that depend on anything else, the reason being that defaults are used when constructing the configuration object. your experiment config node is not yet there when defaults are being evaluated.

**Comment by nicolas-chaulet** [comment]
I think we will pick that up soon. Elements to refactor:

- [ ] Keep config.yaml to a bare defaults section
- [ ] Split segmentation.yaml into multiple files, one file per model
- [ ] Explode the dataset config into multiple files [optional for now]

**Comment by omry** [comment]
This sounds good.
You also have some scaffolding in config.yaml, describing some structure without providing details.
for example:

```yaml
defaults:
  - model: ??? # no default model , must be provided by cli
  - dataset: default_small_dataset # maybe a fast dataset by default for quick iteration

# scaffolding, to be populated by composition.
# just a few general examples of things that might fit (things that should be common to all models all datasets etc.
model: 
   input_size: ???
   output_size: ???
dataset:
  path: ???
```
Another thing:
I am not 100% clear, but it sounds like you have two disjoint tasks (segmentation and classification). it's possible that you want to split them into different main functions with different default files, to allow more flexibility (this way you can get a different defaults list for each).
